openapi: 3.0.1
info:
    title: OfficeVice.GoodVibe.WebApi
    version: "1.0"
paths:
    /good-vibes-points/{userId}:
        get:
            tags:
                - GoodVibesBank
            summary: Get the current number of good vibe for a user
            operationId: GetGoodVibesPoint
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
                      format: uuid
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetGoodVibePointsResult"
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ProblemDetails"
        post:
            summary: Set the number of good vibe for a user
            operationId: SetGoodVibesPoint
            parameters:
                - name: userId
                  in: path
                  required: true
                  schema:
                      type: string
                      format: uuid
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                point:
                                    type: integer
                                    format: int32
                            required:
                                - point
components:
    schemas:
        GetGoodVibePointsResult:
            required:
                - point
            type: object
            properties:
                point:
                    type: integer
                    format: int32
            additionalProperties: false
        ProblemDetails:
            type: object
            properties:
                type:
                    type: string
                    nullable: true
                title:
                    type: string
                    nullable: true
                status:
                    type: integer
                    format: int32
                    nullable: true
                detail:
                    type: string
                    nullable: true
                instance:
                    type: string
                    nullable: true
            additionalProperties: {}
