import type { Plugin } from "./plugin.ts";

interface HeaderPluginOptions {
    header?: string;
}

export function headerPlugin({ header = "This file has been generated by @workleap/create-schemas (https://github.com/workleap/wl-openapi-typescript). Do not modify manually." }: HeaderPluginOptions = {}): Plugin {
    return {
        name: "internal:header-plugin",
        async transform({ code }) {
            return {
                code: `/** ${header} */\n${code}`
            };
        }
    };
}