import type { Plugin } from "./plugin.ts";

interface HeaderPluginOptions {
    header?: string;
}

export function headerPlugin({ header = "Do not modify. This file has been generated by @workleap/create-schemas" }: HeaderPluginOptions = {}): Plugin {
    return {
        name: "internal:header-plugin",
        async transform({ code }) {
            return {
                code: `/** ${header} */\n${code}`
            };
        }
    };
}