/** Do not modify. This file has been generated by @workleap/create-schemas */
import type { paths } from "./types.ts";
import _createClient from "openapi-fetch";

export const createClient = _createClient as typeof _createClient<paths, "application/json">;