/** This file has been generated by @workleap/create-schemas (https://github.com/gsoft-inc/wl-openapi-typescript). Do not modify manually. */
import type { paths } from "./types.ts";
import { createOpenApiHttp } from "openapi-msw";
export const http = createOpenApiHttp<paths>();