/** This file has been generated by @workleap/create-schemas (https://github.com/gsoft-inc/wl-openapi-typescript). Do not modify manually. */
export type GetGoodVibePointsResult = {
    /**
     * @format `int32`
     */
    point: number;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    /**
     * @format `int32`
     */
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
} & Record<string, unknown>;

