/** This file has been generated by @workleap/create-schemas (https://github.com/gsoft-inc/wl-openapi-typescript). Do not modify manually. */

export interface WorkleapClientInit {
    request?: RequestInit;
}

export interface WorkleapClientResponseData<T> {
    data: T;
    error: undefined;
    response: Response;
}

export interface WorkleapClientResponseError<T> {
    data: undefined;
    error: T;
    response: Response;
}

export type WorkleapClientResponse<D, E> = WorkleapClientResponseData<D> | WorkleapClientResponseError<E>;


export class WorkleapClient {
    async fetch(url: string, init: WorkleapClientInit): Promise<WorkleapClientResponse<any, any>> {
        const requestInit = init.request ?? {};
        
        let parsedUrl = url;
        if ("path" in init) {
            const path = init.path;
            for (const key in path) {
                parsedUrl = url.replace(`{${key}}`, path[key].toString());
            }
        }

        const request = new Request(parsedUrl, {
            body: init.body ? JSON.stringify(init.body) : undefined,
            ...requestInit,
            headers: {
                "Content-Type": "application/json",
                ...requestInit.headers
            }
        });

        const response = await fetch(request);

        if (response.ok) {
            return {
                data: await response.clone().json(),
                error: undefined,
                response
            };
        } else {
            return {
                data: undefined,
                error: await response.clone().json(),
                response
            };
        }
    }
}
export interface GetGoodVibesPointInit extends WorkleapClientInit {
    path: {
        userId: string;
    };
}
/**
 * `GET /good-vibes-points/{userId}`
 *
 * Get the current number of good vibe for a user
 */
export function getGoodVibesPoint(client: WorkleapClient, init: GetGoodVibesPointInit): Promise<WorkleapClientResponse<GetGoodVibePointsResult, ProblemDetails>> {
    return client.fetch("/good-vibes-points/{userId}", init);
}

export type GetGoodVibePointsResult = {
    /**
     * @format `int32`
     */
    point: number;
};
export type ProblemDetails = {
    type: string;
    title: string;
    /**
     * @format `int32`
     */
    status: number;
    detail: string;
    instance: string;
};
