/** This file has been generated by @workleap/create-schemas (https://github.com/gsoft-inc/wl-openapi-typescript). Do not modify manually. */

export interface WorkleapClientInit {
    request?: RequestInit;
    parseAs?: "arrayBuffer" | "blob" | "formData" | "json" | "text" | "stream" | "no-parse";
}


type PolyResult<T, U = unknown, V = unknown> =
    T extends "arrayBuffer" ? Result<ArrayBuffer, V>
        : T extends "blob" ? Result<Blob, V>
            : T extends "formData" ? Result<FormData, V>
                : T extends "json" ? Result<U, V>
                    : T extends "text" ? Result<string, V>
                        : T extends "stream" ? Result<ReadableStream<Uint8Array>, V>
                            : T extends "none" ? Result<undefined, V>
                                : Result<U, V>;

export type Result<D, E> = Ok<D> | Err<E>;

export interface Ok<T> {
    ok: true;
    data: T;
    response: Response;
}

export type Err<T> = {
    ok: false;
    error: T;
    response: Response;
} | {
    ok: false;
    error: Error;
    response: undefined;
};

export class WorkleapClient {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async fetch(url: string, init: any = {}): Promise<Result<any, any>> {
        const requestInit = init.request ?? {};
        
        let parsedUrl = url;
        if ("path" in init) {
            const path = init.path;
            for (const key in path) {
                parsedUrl = url.replace(`{${key}}`, path[key].toString());
            }
        }

        const request = new Request(parsedUrl, {
            body: init.body ? JSON.stringify(init.body) : undefined,
            ...requestInit,
            headers: {
                "Content-Type": "application/json",
                ...requestInit.headers
            }
        });

        const response = await fetch(request);

        if (response.ok) {
            return {
                data: await response.clone().json(),
                error: undefined,
                response
            };
        } else {
            return {
                data: undefined,
                error: await response.clone().json(),
                response
            };
        }
    }
}
export interface GetGoodVibesPointInit extends WorkleapClientInit {
    path: {
        userId: string;
    };
}

/**
 * `GET /good-vibes-points/{userId}`
 *
 * Get the current number of good vibe for a user
 */
export function getGoodVibesPoint<T extends GetGoodVibesPointInit>(client: WorkleapClient, init: T): Promise<PolyResult<T["parseAs"], GetGoodVibePointsResult, ProblemDetails>> {
    return client.fetch("/good-vibes-points/{userId}", init);
}


export interface GetGoodVibePointsResult {
    /**
     * @format `int32`
     */
    point: number;
}

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    /**
     * @format `int32`
     */
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
} & Record<string, unknown>;


const result = await getGoodVibesPoint(new WorkleapClient(), { path: { userId: "123" }, parseAs: "stream" });
if (result.ok) {
    const { data } = result;

    return data;
} else {
    const { error, response } = result;
    if (response?.status === 401) {
        return redirect("/login");
    } else {

    }
}