name: CI

# Pnpm setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: true

# Prevent duplicate runs if Renovate falls back to creating a PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Build packages
        run: pnpm build

      - name: Lint packages
        run: pnpm lint

      - name: Test packages
        run: pnpm test
