name: LinearB
description: Report LinearB Deployment

# Based on https://github.com/gsoft-inc/wl-reusable-workflows/blob/main/.github/workflows/linearb-deployment.yml

inputs:
  timestamp:
    description: The timestamp of the start of the workflow
    required: true

runs:
  using: "composite"
  steps:
  - name: 'Report LinearB Deployment'
    shell: pwsh
    run: |
      Write-Host "$(Get-Date -Format "hh:mm:ss")" 'STARTING LinearB Deployment'
      $stage = "${{ inputs.environment }}".ToLowerInvariant()
      $RepositoryUrl = "${{ github.repositoryUrl }}"  -replace "^git://", "https://"
      $data = @"
      {
        "repo_url": "$RepositoryUrl",
        "ref_name": "${{github.sha}}",
        "timestamp": "${{inputs.timestamp}}",
        "stage": "$stage"
      }
      "@

      Write-Host "data ###########################################################"
      Write-Host $data

      Write-Host "Web Request ###########################################################"
      $response = Invoke-WebRequest "https://public-api.linearb.io/api/v1/deployments" -Headers @{"x-api-key"= "${{ secrets.LINEARB_APIKEY }}"} -ContentType "application/json" -Body "$data" -Method Post

      Write-Host "response ##################################################"
      Write-Host $response